
bind = SUPER SHIFT, Y, exec, customlinkopenr "https://www.youtube.com/" "$HOME/.local/share/Hypr-Trinity/icon/youtube.png"

bind = SUPER SHIFT, A, exec, customlinkopenr "https://www.chatgpt.com/" "$HOME/.local/share/Hypr-Trinity/icon/chatgpt.png"

bind = SUPER SHIFT, G, exec, customlinkopenr "https://gemini.google.com/" "$HOME/.local/share/Hypr-Trinity/icon/google-gemini.png" 

# bind = SUPER SHIFT, C, exec, $HOME/.local/share/Hypr-Trinity/bin/custom-open-link.sh "https://calendar.google.com/calendar/" "$HOME/.local/share/Hypr-Trinity/icon/google-calendar.png"

bind = SUPER SHIFT, C, exec, customlinkopenr "https://claude.ai/" "$HOME/.local/share/Hypr-Trinity/icon/claude.png"

bind = SUPER SHIFT, T, exec, customlinkopenr "https://tasks.google.com/" "$HOME/.local/share/Hypr-Trinity/icon/google-tasks.png"

bind = SUPER SHIFT, L, exec, customlinkopenr "https://notebooklm.google.com/" "$HOME/.local/share/Hypr-Trinity/icon/google-notebooklm.png"

bind = SUPER SHIFT, H, exec, customlinkopenr "https://web.whatsapp.com/" "$HOME/.local/share/Hypr-Trinity/icon/whatsapp.png"

bind = SUPER SHIFT, U, exec, customlinkopenr "https://github.com/Avdhut-code/" "$HOME/.local/share/Hypr-Trinity/icon/github-light.png"

bind = SUPER SHIFT, P, exec, customlinkopenr "https://www.perplexity.ai/" "$HOME/.local/share/Hypr-Trinity/icon/perplexity.png"